### ISSUE TITLE
if flags -m and -x are mixed, -m is always used and the generated password is not between -m and -x chars long

### ISSUE THREAD

**Issue by opsec** [wneessen/apg-go#13]
The old c-lang version of apg had options -m and -x (for min and max length of the password)

If one used -m 15 -x 20, the generated password was between 15 and 20 chars long.

The new go version prefers -m before -x, so a -m 4 -x 20 will always produce passwords of length 4.

Can the old behaviour be brought back ?

**Comment by wneessen** [comment]
Thanks for the suggestion, that's definetely a possibility. I'll have a look at it

**Comment by wneessen** [comment]
This has been addressed in release v0.3.1
