### ISSUE TITLE
Add a example in README.md

### ISSUE THREAD

**Issue by clem9669** [wneessen/apg-go#25]
Hey

Nice tool! 
I would be nice to have a GIF or usage section with examples in the README 😄 

👋

**Comment by wneessen** [comment]
Good point. Will be added

**Comment by wneessen** [comment]
Addressed with v0.3.2 (https://github.com/wneessen/apg-go/releases/tag/v0.3.2). I've added a couple of usage examples. If you would like to contribute an animated GIF, please feel free to create a PR for that.
