### ISSUE TITLE
Group password characters in a smart-phone friendly order

### ISSUE THREAD

**Issue by markdingo** [wneessen/apg-go#70]
As we all know, entering a random string of characters with a smartphone touch screen is tedious and error prone due to the need to toggle keypads to gain access to different character tables. 

For example, the four character sequence "**dO#G**" requires the follow 10 keystrokes on iOS.

<sub>\<shift></sub> **d** <sub>\<shift></sub> **O** <sub>\<123></sub> <sub>\<#+=></sub> **#** <sub>\<ABC></sub> <sub>\<shift></sub>  **G**

(Where <sub>\<keypad></sub> identifies a keypad selection).

This makes entering a reasonable secure random password an excruciating process.

One solution is to group the string in keypad order, e.g, all the lower case letters first, then the upper case letters, then the unshifted specials and finally the shifted specials and thus significantly reducing the times a <sub>\<shift></sub> keystroke is needed as well as the number of keyboard context switches for your brain.

For example, the sequence "Fj#Wr@eLxP9z]9eL" might be regrouped as "FWLPjwrexze99@]#".

There are probably other ordering sequences which simplify smartphone typing, such as those who type with two thumbs in which case the characters might be alternately selected from the left-hand side then the right-hand side.

Hopefully the benefits are pretty obvious, however there are a number of arguments against the idea:

1.  Obviously any predictable ordering reduces keyspace size for a given length, though the grouping order can still be randomized somewhat as well as the size of the group to increase keyspace size a bit. But when enabled, such a feature should probably recommend increasing key length. Having said that, PINs and the other constrained keyspace sets are vastly smaller per character, so it's not entirely doom and gloom on the security front.

2. Different operating systems have different keypads, so it might need to be optioned for Android, iOS, etc. which could change their keypad in a future release. It might get a bit unwieldy if selection has to be made by platform/os/language/version.

3. Some apps on some platforms can select or use custom keypads which might thwart the benefit of grouping in some cases.

4. One could argue that you should just use a password manager which potentially lets you cut and paste. But some of us don't trust password managers (which is why we use standalone password managers like apg!) and too many websites think it improves security to disallow cut/paste for their password fields.

So this is not necessarily a compelling feature, but it might be useful enough to some.

**Comment by wneessen** [comment]
Hi @markdingo,

I've created a test method that would in my opinion accomplish your request. Here is a test run with it for 10 random PWs. Let me know if this is what you are looking for:

```
Raw: PX4xDoiKrs,[egEAief{ => Grouped: ADEKPXeefgiiorsx4,[{
Raw: *Z%C9d+PZYkD7D+{~r'w => Grouped: CDDPYZZdkrw79%'*++{~
Raw: 4?r2YV:Abo&/z<3tJ*Z{ => Grouped: AJVYZbortz234&*/:<?{
Raw: .BrX*.=k"spdb@\*r26; => Grouped: BXbdkprrs26"**..;=@\
Raw: #/FABD3O|1DZeKtDw/%? => Grouped: ABDDDFKOZetw13#%//?|
Raw: 0B/4w2+=\OX*Ex&+]yN8 => Grouped: BENOXwxy0248&*++/=\]
Raw: .aOken"5"1L>arHlVo]] => Grouped: HLOVaaeklnor15"".>]]
Raw: 01zurd8K<6}NEeAdr{o: => Grouped: AEKNddeorruz0168:<{}
Raw: )be}IkQsAj2PH'EDN1Bp => Grouped: ABDEHINPQbejkps12')}
Raw: 0I&MgqzsC'|_HQ)cT~Z\ => Grouped: CHIMQTZcgqsz0&')\_|~
```

If so, I'll add a new CLI arg that, if set, will group the PWs accordingly.

**Comment by wneessen** [comment]
Nevermind... I just realized that I am not only grouping, but also sorting, which makes the PWs much more predictable. Looks like I have to rework that method a bit.

**Comment by wneessen** [comment]
This should be better now:

```
Raw: PX4xDoiKrs,[egEAief{ => Grouped: PXDKEAxoirsegief4,[{
Raw: *Z%C9d+PZYkD7D+{~r'w => Grouped: ZCPZYDDdkrw97*%++{~'
Raw: 4?r2YV:Abo&/z<3tJ*Z{ => Grouped: YVAJZrbozt423?:&/<*{
Raw: .BrX*.=k"spdb@\*r26; => Grouped: BXrkspdbr26.*.="@\*;
Raw: #/FABD3O|1DZeKtDw/%? => Grouped: FABDODZKDetw31#/|/%?
Raw: 0B/4w2+=\OX*Ex&+]yN8 => Grouped: BOXENwxy0428/+=\*&+]
Raw: .aOken"5"1L>arHlVo]] => Grouped: OLHVakenarlo51."">]]
Raw: 01zurd8K<6}NEeAdr{o: => Grouped: KNEAzurdedro0186<}{:
Raw: )be}IkQsAj2PH'EDN1Bp => Grouped: IQAPHEDNBbeksjp21)}'
Raw: 0I&MgqzsC'|_HQ)cT~Z\ => Grouped: IMCHQTZgqzsc0&'|_)~\
```

**Comment by markdingo** [comment]
Yes, the second grouping looks much better. It'll be interesting to see your CLI/API choices. I think that might be more challenging than the grouping code :-)

**Comment by wneessen** [comment]
The feature is now merged into the main branch. You can now use the `-g` flag to enable the grouping. If you have Docker available, you can test using the main build: `docker pull ghcr.io/wneessen/apg-go:main`
Please let me know if this works for you.
