### ISSUE TITLE
Installation documentation should include "go install" instructions

### ISSUE THREAD

**Issue by markdingo** [wneessen/apg-go#93]
The project has obviously gone to a lot of trouble to ensure packages, executables and docker images are readily available so it's somewhat surprising that this go project doesn't document the use of "go install github.com/wneessen/apg-go/cmd/apg@latest" as a way of slurping down the latest sources and compiling and installing locally.

The big advantage of the "go install" approach is that we don't have to worry about whether the distributions have updated to the latest versions, particularly if you want to test a recent feature.

I do note that the go.mod requires 1.22 which is more recent than a lot of go distributions (Debian, FreeBSD to name just two) so currently "go install" is a bit constrained, but assuming there is no special need to bump go.mod, as time goes by the "go install" method will work on more and more standard distributions.

**Comment by wneessen** [comment]
Thanks for the issue, @markdingo. Good point. Will add it.

**Comment by markdingo** [comment]
NIce work. Thanks for accepting my issue (of which this is the second).

Good luck with the project. It deserves to do well.

**Comment by wneessen** [comment]
Appreciate the feedback :)
